In [3]:
import cw07
import numpy as np
import pandas as pd

# Classwork 07

Jacob Anabi, Grady Lynch

10-09-2018

## Instructions

First, go through the slides indicated in the README and place any code fragments to test in the following subsection. Second, go through the rest of the notebook, execute lines to test them, and complete the coding assignments.

### Slide Scratch Work

#### Numpy Arrays Performance

In [11]:
%timeit l = range(100000)
%timeit lnp = np.arange(100000) # numpy performance (should be faster)

362 ns ± 53.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


94.9 µs ± 2.83 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### Numpy Universal Functions

In [12]:
%time x = np.linspace(-100,100,1000000) # numpy performance (should be faster)
D = 5.0
x0 = -3.5
%time g = (1.0/np.sqrt(2*np.pi*D))*np.exp(-(x - x0)**2/(2*D))

CPU times: user 6.48 ms, sys: 60 µs, total: 6.54 ms
Wall time: 4.94 ms
CPU times: user 28.3 ms, sys: 12 ms, total: 40.3 ms
Wall time: 40 ms


#### Numpy Vectorizing Functions

In [14]:
x = np.arange(1,100)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
def f(x):
    if x%2==0:
        return "Even"
    else:
        return "Odd"

fv = np.vectorize(f)
fv(x)

array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd',
       'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd'],
      dtype='<U4')

#### Array Views

In [16]:
l = np.arange(20)
l

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
l_3d = np.reshape(l, (2,2,5))
l_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [18]:
l_3d[1,1,4]

19

In [20]:
l[0:4] = 999
l_3d[1,1,2:] = -1

In [21]:
l_3d

array([[[999, 999, 999, 999,   4],
        [  5,   6,   7,   8,   9]],

       [[ 10,  11,  12,  13,  14],
        [ 15,  16,  -1,  -1,  -1]]])

## Description

The following code benchmarks and plots functions approximated both as python lists and as numpy arrays.

### Module Documentation

For illustration, here is a reminder of how the python help system naturally uses the docstrings from the code.

In [0]:
help(cw07)

In [0]:
help(cw07.gen_gaussian_list)

In [0]:
?cw07.gen_gaussian_array

### Python Lists

Benchmark and plot the reference list implementation.

#### Gaussian Function

In [0]:
%time x, g = cw07.gen_gaussian_list(-10,10,1000001)

In [0]:
gauss = pd.DataFrame({"x":x,"g(x)":g})

In [0]:
gauss

In [0]:
gauss.plot(x="x",y="g(x)")

### Numpy Arrays

#### Gaussian Function

In [0]:
%time x, g = cw07.gen_gaussian_array(-10, 10, 1000001)

In [0]:
gauss = pd.DataFrame({"x":x,"g(x)":g})

In [0]:
gauss.plot(x="x",y="g(x)")

## Conclusions

Place your conclusion about your investigations at the end in a well-written conclusion section.